version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ProductManagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-api
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ProductManagement;Username=postgres;Password=123456
      - ASPNETCORE_ENVIRONMENT=Development 
    ports:
      - "5000:5000"
    restart: always

volumes:
  postgres_data:
