version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ProductManagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: ProductManagement.API/Dockerfile
    container_name: product-management
    depends_on:
      - postgres
      - localstack   
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ProductManagement;Username=postgres;Password=123456
      - ASPNETCORE_ENVIRONMENT=Development 
      - AWS_SERVICE_URL=http://localstack:4566 
      - AWS_BUCKET_NAME=product-images
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    ports:
      - "5000:5000"
    restart: always
  
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEFAULT_REGION=us-east-1
    ports:
      -  "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-init.sh:/etc/localstack/init/ready.d/init-s3.sh"
volumes:
  postgres_data:
